### ISSUE TITLE
[🌈 Feature] 배포 자동화

### ISSUE THREAD

**Issue by greeng00se** [woowa-chat/backend#23]
## **🌈 추가할 기능에 대한 설명**

Jenkins를 사용해서 CI/CD 설정을 하려고해 내가 예전에 했던 [게시물](https://greeng00se.tistory.com/133)을 참고하여 진행할꺼고
동일하게 빌드 -> 테스트 -> S3 업로드 -> elasticbeanstalk 배포 순으로 파이프라인을 설정하려고 해

추가로 말랑도 알아야하니까 담주 시간 될 때 인스턴스 통째로 날려버리고 새로 다시 설정해 볼 생각이야

**Comment by shin-mallang** [comment]
오키오키 나도 공부해갈게~!

**Comment by greeng00se** [comment]
완료~

**Comment by shin-mallang** [comment]
고생했어~! 인프라 초고수 허브..
