### ISSUE TITLE
[🌈 Feature] 전체 글 조회 시 QnA 수 같이 반환하는 기능 추가

### ISSUE THREAD

**Issue by greeng00se** [woowa-chat/backend#24]
## **🌈 추가할 기능에 대한 설명**

전체 글 조회시 첫 답변을 같이 반환하면 좋을 것 같아.

게시물을 보는데 아래와 같이 간단한 형식으로 되어있어서 조금 더 살을 추가해보려고
<img width="818" alt="image" src="https://user-images.githubusercontent.com/58586537/235207966-2d05421c-79c6-4042-8fc9-91d6767209fb.png">

그리고 또 어떤걸 추가하면 좋을지 생각중이야
답변의 개수를 추가할지 생각중인데 현재 반환하는 데이터로 충분히 구할 수 있는 데이터라 추가적인 반환값의 변경은 필요없을 것 같아

**Comment by shin-mallang** [comment]
이게 근데 지금은 첫 질문이 제목으로 설정한건데, 우리 추가할 기능으로 제목을 바꾸는 기능 추가할 예정이었지 않아?
지금 이 기능을 만들면 나중에 조금 이상해지지 않을까?

**Comment by greeng00se** [comment]
굳 그러면 메시지의 개수를 반환해주면 좋을 것 같아

**Comment by shin-mallang** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/52229930/235298129-94bbd841-52ca-4c21-a7c5-8b316f8c5f3a.png">
간단하게 이렇게 수정해봤는데, 이러면 쿼리가 1번 더 발생해야하는데 괜찮지?

**Comment by greeng00se** [comment]
채팅 하나당이 아니라 IN절로 쿼리 들어가니까 1 + 1이겠지? 그럼 크게 상관없을 듯!

**Comment by shin-mallang** [comment]
역시 허브갓
수정하겠습니당~!
