### ISSUE TITLE
[🌈 Feature] 질문 요청시 토큰 받는 부분 제거

### ISSUE THREAD

**Issue by greeng00se** [woowa-chat/backend#25]
## **🌈 추가할 기능에 대한 설명**

라이브러리를 사용해보려고 했는데 nuxt에서 작동이 잘 안되는 것 같더라고(설정을 어떻게 해야할지 모르겠어)
질문에 대한 토큰을 프론트엔드에서 계산해서 넘겨주는건 이상한 것 같기도 하고

만약 토큰을 계산한다면, 대략적으로 계산하는 로직을 우리가 작성해도 될 것 같아
한글의 경우 한 글자당 대략 3토큰이라 질문이 모두 한글로 들어온다고 가정하고
(질문의 길이 * 3) - (빈칸 갯수 * 2) 정도로 간단하게 구하는거지

**Comment by shin-mallang** [comment]
오키오키! 
이 부분은 한번 고민해서 처리해볼게!
GPT API에서 응답 보내면 답변 토큰이랑 전체 토큰 알려줘서, 이거 가지고 처리해볼 수도 있을 것 같아.

**Comment by greeng00se** [comment]
말랑 고순데요?
