### ISSUE TITLE
[🐞 BUG] 정보를 수정해도 회원가입시 설정한 코스로 적용되는 문제 

### ISSUE THREAD

**Issue by greeng00se** [woowa-chat/backend#26]
## **🐞 BUG에 대해서 설명해주세요**

정보를 수정해도 회원가입시 설정한 코스로 적용되는 문제 

닉네임과 코스를 보내는데 코스가 변경되면 같이 변경되도록 적용하면 좋을 것 같아

**Comment by shin-mallang** [comment]
이미 가입된 사람의 코스를 변경하는 기능을 의미하는거야?

**Comment by greeng00se** [comment]
예압! 회원가입 + 수정 기능을 한 번에? 덮어쓰기하는 느낌으로
나중가면 회원가입 수정 분리해야될 것 같긴한데 지금은 그냥 그렇게 해도 될 것 같아서

**Comment by shin-mallang** [comment]
그럼 코스도 header에 같이 보내는거???
