### ISSUE TITLE
[🌈 Feature] Flyway 적용하기

### ISSUE THREAD

**Issue by shin-mallang** [woowa-chat/backend#27]
## **🌈 추가할 기능에 대한 설명**
- [x] Flyway를 적용한다

**Comment by shin-mallang** [comment]
이거 내가 잘 몰라서 그런데, db/migration 폴더에 sql 파일 그대로 올려놓으면 보안상 문제가 없을까?

**Comment by greeng00se** [comment]
괜찮을듯~ 보안 생각한다면 private repo를 사용하는게 맞을듯!
